name: Build site on main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - run: pnpm install --frozen-lockfile
      - name: Copy Data From gh-pages
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          src_path: /data
          src_branch: gh-pages
          dst_path: /public/data
          dst_owner: tomchentw
          dst_repo_name: taipower
      - run: pnpm build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out