name: Build site on main branch update

on:
  push:
    branches:
      - main

jobs:
  copy-github-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy .github
        run: |
            git config user.name 'Tom Chen'
            git config user.email 'developer@tomchentw.com'
            git switch gh-pages
            git rm -rf .github
            git restore --source=origin/main .github
            git add .github
            git commit -m "deploy: $GITHUB_SHA"
            git push

  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - uses: actions/cache@v2
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          exclude_assets: 'data' # Also ensure .github folder is published
          github_token: ${{ secrets.GITHUB_TOKEN }} # Do NOT use ACTIONS_DEPLOY_KEY here since this will trigger infinite loop on exec-cron.yml
          publish_dir: ./out