name: Run cron script on scheulde

on:
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "5/5 1/1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - run: pnpm install
      - run: pnpm cron
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update data"
          branch: main
