name: Run accumulate script

on:
  push:
    branches:
      - gh-pages

jobs:
  run-accumulate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - uses: actions/cache@v2
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm cron accumulate
      - run: |
          git config user.name 'Tom Chen'
          git config user.email 'developer@tomchentw.com'
          git switch gh-pages
          git rm -rf data
          mv public/data data
          git add data
          git commit -m "deploy: $(git rev-parse HEAD)"
          git push
